name: Continuous Integration

on:
  workflow_dispatch:

jobs:
  ci:
    name: Rust CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PSE
        uses: invisirisk/pse-action@develop
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Build project
        run: cargo build --workspace

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@develop
        with:
          cleanup: "true"
